CREATE TABLE "Game" (
  "game_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "publisher" varchar(255),
  "developer" varchar(255),
  "release_date" date,
  "genre" varchar(100),
  "image_url" varchar(512)
);

CREATE TABLE "Review" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "hours_played" decimal(10,2) NOT NULL,
  "completed" boolean NOT NULL,
  "rating" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "location" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "UserGame" (
  "user_id" int,
  "game_id" int,
  "added_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("user_id", "game_id")
);

CREATE INDEX ON "Game" ("title");

CREATE INDEX ON "Review" ("game_id", "user_id");

CREATE INDEX ON "Review" ("user_id");

CREATE INDEX ON "User" ("username");

CREATE INDEX ON "User" ("email");

CREATE INDEX ON "UserGame" ("user_id");

CREATE INDEX ON "UserGame" ("game_id");

COMMENT ON COLUMN "Review"."rating" IS 'CHECK (rating >= 1 AND rating <= 10)';

ALTER TABLE "Review" ADD FOREIGN KEY ("game_id") REFERENCES "Game" ("game_id");

ALTER TABLE "Review" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "UserGame" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "UserGame" ADD FOREIGN KEY ("game_id") REFERENCES "Game" ("game_id");
