"""add is_admin field to User model

Revision ID: 2f1de53f4697
Revises: 533164a076f7
Create Date: 2024-08-12 13:45:05.428974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1de53f4697'
down_revision = '533164a076f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET is_admin = FALSE')
    op.alter_column('user', 'is_admin', nullable=False)
    # ### end Alembic commands ###
def downgrade():
    op.drop_column('user', 'is_admin')
