"""update User class

Revision ID: 82fd68aa7825
Revises: bd55672a48c8
Create Date: 2024-07-16 20:15:11.283205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fd68aa7825'
down_revision = 'bd55672a48c8'
branch_labels = None
depends_on = None

    # ### commands auto generated by Alembic - please adjust! ###
       # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
